updated and build windows only

diff --git a/.github/workflows/electron-sandbox.yml b/.github/workflows/electron-sandbox.yml
--- a/.github/workflows/electron-sandbox.yml
+++ b/.github/workflows/electron-sandbox.yml
@@ -29,11 +29,11 @@ jobs:
         - name: Publish
           run: |
             yarn run dist 
-        - name: Cleanup artifacts Linux and macOS
-          if: matrix.os != 'windows-latest'
-          run: |
-                mkdir artifacts
-                cp -R dist/{*.deb,*.dmg,*.AppImage} artifacts || true
+        # - name: Cleanup artifacts Linux and macOS
+        #   if: matrix.os != 'windows-latest'
+        #   run: |
+        #         mkdir artifacts
+        #         cp -R dist/{*.deb,*.dmg,*.AppImage} artifacts || true
         - name: Cleanup artifacts Windowns
           if: matrix.os == 'windows-latest'
           run: |
